services:
  - type: web
    name: population-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"